apiVersion: v1
kind: Namespace
metadata:
  name: dragonfly
---
apiVersion: dragonflydb.io/v1alpha1
kind: Dragonfly
metadata:
  name: dragonfly
  namespace: dragonfly
spec:
  replicas: 1

  image: docker.dragonflydb.io/dragonflydb/dragonfly:v1.23.1

  resources:
    requests:
      memory: "256Mi"
      cpu: "100m"
    limits:
      memory: "1Gi"
      cpu: "500m"

  args:
    - --maxmemory=768mb
    - --proactor_threads=2
    - --cache_mode=true

  serviceSpec:
    type: ClusterIP
