extends: default

rules:
  line-length:
    max: 100
    level: warning
  indentation:
    spaces: 2
    indent-sequences: true
  new-lines:
    type: unix
  new-line-at-end-of-file: enable
  trailing-spaces: enable
  document-start: disable
  braces:
    min-spaces-inside: 0
    max-spaces-inside: 0
  brackets:
    min-spaces-inside: 0
    max-spaces-inside: 0
  colons:
    max-spaces-before: 1
  comments:
    min-spaces-from-content: 1
  truthy:
    allowed-values: ['true', 'false', 'on', 'off']

ignore: |-
  alembic/
  .venv/
  infra/k8s/charts/*/templates/
  infra/k8s/secrets/
