continue_on_error: true
formatter:
  type: basic
  indent: 2
  line_ending: lf
  max_line_length: 100
  retain_line_breaks: true
  trim_trailing_whitespace: true
doublestar: true
include:
  - "**/*.yaml"
  - "**/*.yml"
  - "*.yml"
  - "*.yaml"
exclude:
  - "alembic/**/*.yaml"
  - "infra/k8s/charts/worker/templates/*.yaml"
  - "infra/k8s/charts/gateway/templates/*.yaml"

