externalSecrets:
  create: ENC[AES256_GCM,data:CR4t6w==,iv:eeTDCHMOBg5g5M6weAoD7dTERgqhP3wyTQkIpJpy28s=,tag:9JdpdtwvZebcDK+TOpC78w==,type:bool]
  data:
    LLAMAINDEX_OPENAI_API_KEY: ENC[AES256_GCM,data:CSpOuSEMLCIRUA==,iv:AB/jt5c6Q1ByHsnc5Vc6U0op0OftuXmR9FezGkpigWs=,tag:37FR5iARu7fnPgJCLT5PZw==,type:str]
    LLM_BINDING_API_KEY: ENC[AES256_GCM,data:vJbnG7bh+JJAZw==,iv:xa/6iKEwTWz9PhCPH4SP3ZE+G8cEiDFv2HqACaPHoRI=,tag:Xzdslk+/FvNDI57tuhyKTQ==,type:str]
    EMBEDDING_BINDING_API_KEY: ENC[AES256_GCM,data:iK27/3arWlJKdQ==,iv:2L7h8HMC8qQX2mwX5HEUgVP4O4lqu0pHpJA9jfnWTvQ=,tag:A5IANTj+24M9jf2fd1+wLw==,type:str]
sops:
  age:
    - recipient: age1vn6s5506umxxqn7rdchw2257fvetar88wsdfa5l4pm7hwt357s9su4hnc8
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAyemkza1c5UEpLY3dLMGtI
        MG5NbjVDbzFyK2dPb0MzcXluRlJaM1c5SFI0ClJnR09MdU9ybnRTemJJTEloTXVr
        MGJ0VmY1KzYyWDlTUG5wMFdYQWJpNWsKLS0tIGdvZ1VudzZyOFV2RldlRnpqVEFs
        TjhTTVJUQ21nTEpVaEJ4Rk1SMDZveFEK4ffrMIw9Ohy7EKdaqfX17yzhtl67CcPc
        bf1cg6TxA+UfEOaT80iPu1ciB30qMfSIGiBXl+NEDV+26o+kp7qoOw==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2026-01-22T04:45:48Z"
  mac: ENC[AES256_GCM,data:IRbplUzTh/OKq7lWvmB/gCR8wKZk+hInmV2R+DeVJdqiUFnOuEBzUY/C7Q0MlHdWXdei6KEJsTlDEYP8b/OyXZkXT5XEJppsTdv3BMpV41KN4WAseVWCC070OCLHw85t138j0goW6MBLxUzVQ4U7RWG1YWIK/4BgxG/j5eaGPBI=,iv:aCSljLFwuIxRQqnsHd6kqaUolhdx7vv2xj3TvHjEMKc=,tag:PYBS5wdHyfdLtKXBMdSA9Q==,type:str]
  unencrypted_suffix: _unencrypted
  version: 3.11.0
