"""Initial schema: inbox table only (libraries manage their own)

Revision ID: 84b435351e1f
Revises: 
Create Date: 2026-01-07 03:39:35.300404

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '84b435351e1f'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('idx_llamaindex_kg_nodes_embedding'), table_name='llamaindex_kg_nodes', postgresql_ops={'embedding': 'vector_cosine_ops'}, postgresql_using='hnsw')
    op.drop_index(op.f('idx_llamaindex_kg_nodes_node_id'), table_name='llamaindex_kg_nodes')
    op.drop_index(op.f('idx_llamaindex_kg_nodes_properties'), table_name='llamaindex_kg_nodes', postgresql_using='gin')
    op.drop_index(op.f('idx_llamaindex_kg_nodes_type'), table_name='llamaindex_kg_nodes')
    op.drop_table('llamaindex_kg_nodes')
    op.drop_index(op.f('idx_mem0_memory_index_created_at'), table_name='mem0_memory_index')
    op.drop_index(op.f('idx_mem0_memory_index_embedding'), table_name='mem0_memory_index', postgresql_ops={'embedding': 'vector_cosine_ops'}, postgresql_using='hnsw')
    op.drop_index(op.f('idx_mem0_memory_index_type'), table_name='mem0_memory_index')
    op.drop_index(op.f('idx_mem0_memory_index_user_id'), table_name='mem0_memory_index')
    op.drop_table('mem0_memory_index')
    op.drop_index(op.f('idx_mem0_user_facts_category'), table_name='mem0_user_facts')
    op.drop_index(op.f('idx_mem0_user_facts_embedding'), table_name='mem0_user_facts', postgresql_ops={'embedding': 'vector_cosine_ops'}, postgresql_using='hnsw')
    op.drop_index(op.f('idx_mem0_user_facts_metadata'), table_name='mem0_user_facts', postgresql_using='gin')
    op.drop_index(op.f('idx_mem0_user_facts_user_id'), table_name='mem0_user_facts')
    op.drop_table('mem0_user_facts')
    op.drop_index(op.f('idx_llamaindex_kg_edges_properties'), table_name='llamaindex_kg_edges', postgresql_using='gin')
    op.drop_index(op.f('idx_llamaindex_kg_edges_source'), table_name='llamaindex_kg_edges')
    op.drop_index(op.f('idx_llamaindex_kg_edges_target'), table_name='llamaindex_kg_edges')
    op.drop_index(op.f('idx_llamaindex_kg_edges_type'), table_name='llamaindex_kg_edges')
    op.drop_index(op.f('idx_llamaindex_kg_edges_unique'), table_name='llamaindex_kg_edges')
    op.drop_table('llamaindex_kg_edges')
    op.drop_index(op.f('idx_llamaindex_documents_content_hash'), table_name='llamaindex_documents')
    op.drop_index(op.f('idx_llamaindex_documents_doc_id'), table_name='llamaindex_documents')
    op.drop_index(op.f('idx_llamaindex_documents_embedding'), table_name='llamaindex_documents', postgresql_ops={'embedding': 'vector_cosine_ops'}, postgresql_using='hnsw')
    op.drop_index(op.f('idx_llamaindex_documents_metadata'), table_name='llamaindex_documents', postgresql_using='gin')
    op.drop_table('llamaindex_documents')
    op.alter_column('inbox', 'target',
               existing_type=sa.VARCHAR(length=50),
               nullable=False,
               existing_server_default=sa.text("'all'::character varying"))
    op.alter_column('inbox', 'processed',
               existing_type=sa.BOOLEAN(),
               nullable=False,
               existing_server_default=sa.text('false'))
    op.alter_column('inbox', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('CURRENT_TIMESTAMP'))
    op.drop_index(op.f('idx_inbox_created_at'), table_name='inbox')
    op.create_index('idx_inbox_created_at', 'inbox', ['created_at'], unique=False, postgresql_ops={'created_at': 'DESC'})
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('idx_inbox_created_at', table_name='inbox', postgresql_ops={'created_at': 'DESC'})
    op.create_index(op.f('idx_inbox_created_at'), 'inbox', [sa.literal_column('created_at DESC')], unique=False)
    op.alter_column('inbox', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('CURRENT_TIMESTAMP'))
    op.alter_column('inbox', 'processed',
               existing_type=sa.BOOLEAN(),
               nullable=True,
               existing_server_default=sa.text('false'))
    op.alter_column('inbox', 'target',
               existing_type=sa.VARCHAR(length=50),
               nullable=True,
               existing_server_default=sa.text("'all'::character varying"))
    op.create_table('llamaindex_documents',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), autoincrement=False, nullable=False),
    sa.Column('doc_id', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.Column('content', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('content_hash', sa.VARCHAR(length=64), autoincrement=False, nullable=False),
    sa.Column('embedding', sa.NullType(), autoincrement=False, nullable=True),
    sa.Column('metadata', postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("'{}'::jsonb"), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('CURRENT_TIMESTAMP'), autoincrement=False, nullable=True),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('CURRENT_TIMESTAMP'), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('llamaindex_documents_pkey')),
    sa.UniqueConstraint('doc_id', name=op.f('llamaindex_documents_doc_id_key'), postgresql_include=[], postgresql_nulls_not_distinct=False)
    )
    op.create_index(op.f('idx_llamaindex_documents_metadata'), 'llamaindex_documents', ['metadata'], unique=False, postgresql_using='gin')
    op.create_index(op.f('idx_llamaindex_documents_embedding'), 'llamaindex_documents', ['embedding'], unique=False, postgresql_ops={'embedding': 'vector_cosine_ops'}, postgresql_using='hnsw')
    op.create_index(op.f('idx_llamaindex_documents_doc_id'), 'llamaindex_documents', ['doc_id'], unique=False)
    op.create_index(op.f('idx_llamaindex_documents_content_hash'), 'llamaindex_documents', ['content_hash'], unique=True)
    op.create_table('llamaindex_kg_edges',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), autoincrement=False, nullable=False),
    sa.Column('source_node_id', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.Column('target_node_id', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.Column('edge_type', sa.VARCHAR(length=100), autoincrement=False, nullable=False),
    sa.Column('properties', postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("'{}'::jsonb"), autoincrement=False, nullable=True),
    sa.Column('weight', sa.DOUBLE_PRECISION(precision=53), server_default=sa.text('1.0'), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('CURRENT_TIMESTAMP'), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['source_node_id'], ['llamaindex_kg_nodes.node_id'], name=op.f('llamaindex_kg_edges_source_node_id_fkey'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['target_node_id'], ['llamaindex_kg_nodes.node_id'], name=op.f('llamaindex_kg_edges_target_node_id_fkey'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('llamaindex_kg_edges_pkey'))
    )
    op.create_index(op.f('idx_llamaindex_kg_edges_unique'), 'llamaindex_kg_edges', ['source_node_id', 'target_node_id', 'edge_type'], unique=True)
    op.create_index(op.f('idx_llamaindex_kg_edges_type'), 'llamaindex_kg_edges', ['edge_type'], unique=False)
    op.create_index(op.f('idx_llamaindex_kg_edges_target'), 'llamaindex_kg_edges', ['target_node_id'], unique=False)
    op.create_index(op.f('idx_llamaindex_kg_edges_source'), 'llamaindex_kg_edges', ['source_node_id'], unique=False)
    op.create_index(op.f('idx_llamaindex_kg_edges_properties'), 'llamaindex_kg_edges', ['properties'], unique=False, postgresql_using='gin')
    op.create_table('mem0_user_facts',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), autoincrement=False, nullable=False),
    sa.Column('user_id', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.Column('fact', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('category', sa.VARCHAR(length=100), autoincrement=False, nullable=True),
    sa.Column('confidence', sa.DOUBLE_PRECISION(precision=53), server_default=sa.text('1.0'), autoincrement=False, nullable=True),
    sa.Column('embedding', sa.NullType(), autoincrement=False, nullable=True),
    sa.Column('metadata', postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("'{}'::jsonb"), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('CURRENT_TIMESTAMP'), autoincrement=False, nullable=True),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('CURRENT_TIMESTAMP'), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('mem0_user_facts_pkey'))
    )
    op.create_index(op.f('idx_mem0_user_facts_user_id'), 'mem0_user_facts', ['user_id'], unique=False)
    op.create_index(op.f('idx_mem0_user_facts_metadata'), 'mem0_user_facts', ['metadata'], unique=False, postgresql_using='gin')
    op.create_index(op.f('idx_mem0_user_facts_embedding'), 'mem0_user_facts', ['embedding'], unique=False, postgresql_ops={'embedding': 'vector_cosine_ops'}, postgresql_using='hnsw')
    op.create_index(op.f('idx_mem0_user_facts_category'), 'mem0_user_facts', ['category'], unique=False)
    op.create_table('mem0_memory_index',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), autoincrement=False, nullable=False),
    sa.Column('user_id', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.Column('memory_type', sa.VARCHAR(length=50), autoincrement=False, nullable=False),
    sa.Column('content', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('embedding', sa.NullType(), autoincrement=False, nullable=True),
    sa.Column('metadata', postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("'{}'::jsonb"), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('CURRENT_TIMESTAMP'), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('mem0_memory_index_pkey'))
    )
    op.create_index(op.f('idx_mem0_memory_index_user_id'), 'mem0_memory_index', ['user_id'], unique=False)
    op.create_index(op.f('idx_mem0_memory_index_type'), 'mem0_memory_index', ['memory_type'], unique=False)
    op.create_index(op.f('idx_mem0_memory_index_embedding'), 'mem0_memory_index', ['embedding'], unique=False, postgresql_ops={'embedding': 'vector_cosine_ops'}, postgresql_using='hnsw')
    op.create_index(op.f('idx_mem0_memory_index_created_at'), 'mem0_memory_index', [sa.literal_column('created_at DESC')], unique=False)
    op.create_table('llamaindex_kg_nodes',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), autoincrement=False, nullable=False),
    sa.Column('node_id', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.Column('node_type', sa.VARCHAR(length=100), autoincrement=False, nullable=False),
    sa.Column('properties', postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("'{}'::jsonb"), autoincrement=False, nullable=True),
    sa.Column('embedding', sa.NullType(), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('CURRENT_TIMESTAMP'), autoincrement=False, nullable=True),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('CURRENT_TIMESTAMP'), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('llamaindex_kg_nodes_pkey')),
    sa.UniqueConstraint('node_id', name=op.f('llamaindex_kg_nodes_node_id_key'), postgresql_include=[], postgresql_nulls_not_distinct=False)
    )
    op.create_index(op.f('idx_llamaindex_kg_nodes_type'), 'llamaindex_kg_nodes', ['node_type'], unique=False)
    op.create_index(op.f('idx_llamaindex_kg_nodes_properties'), 'llamaindex_kg_nodes', ['properties'], unique=False, postgresql_using='gin')
    op.create_index(op.f('idx_llamaindex_kg_nodes_node_id'), 'llamaindex_kg_nodes', ['node_id'], unique=False)
    op.create_index(op.f('idx_llamaindex_kg_nodes_embedding'), 'llamaindex_kg_nodes', ['embedding'], unique=False, postgresql_ops={'embedding': 'vector_cosine_ops'}, postgresql_using='hnsw')
    # ### end Alembic commands ###
