"""Initial schema: inbox table only (libraries manage their own)

Revision ID: 84b435351e1f
Revises:
Create Date: 2026-01-07 03:39:35.300404

"""

from collections.abc import Sequence

import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "84b435351e1f"
down_revision: str | Sequence[str] | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "inbox",
        "target",
        existing_type=sa.VARCHAR(length=50),
        nullable=False,
        existing_server_default=sa.text("'all'::character varying"),
    )
    op.alter_column(
        "inbox",
        "processed",
        existing_type=sa.BOOLEAN(),
        nullable=False,
        existing_server_default=sa.text("false"),
    )
    op.alter_column(
        "inbox",
        "created_at",
        existing_type=postgresql.TIMESTAMP(timezone=True),
        nullable=False,
        existing_server_default=sa.text("CURRENT_TIMESTAMP"),
    )
    op.drop_index(op.f("idx_inbox_created_at"), table_name="inbox")
    op.create_index(
        "idx_inbox_created_at",
        "inbox",
        ["created_at"],
        unique=False,
        postgresql_ops={"created_at": "DESC"},
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index("idx_inbox_created_at", table_name="inbox", postgresql_ops={"created_at": "DESC"})
    op.create_index(
        op.f("idx_inbox_created_at"), "inbox", [sa.literal_column("created_at DESC")], unique=False
    )
    op.alter_column(
        "inbox",
        "created_at",
        existing_type=postgresql.TIMESTAMP(timezone=True),
        nullable=True,
        existing_server_default=sa.text("CURRENT_TIMESTAMP"),
    )
    op.alter_column(
        "inbox",
        "processed",
        existing_type=sa.BOOLEAN(),
        nullable=True,
        existing_server_default=sa.text("false"),
    )
    op.alter_column(
        "inbox",
        "target",
        existing_type=sa.VARCHAR(length=50),
        nullable=True,
        existing_server_default=sa.text("'all'::character varying"),
    )
    # ### end Alembic commands ###
