apiVersion: v1
kind: ConfigMap
metadata:
  name: worker-config
  namespace: mycontextprotocol
data:
  DRAGONFLY_HOST: {{ .Values.config.dragonfly.host | quote }}
  DRAGONFLY_PORT: {{ .Values.config.dragonfly.port | quote }}
  QUEUE_NAME: {{ .Values.config.dragonfly.queueName | quote }}
  
  LLAMAINDEX_POSTGRES_HOST: {{ .Values.config.llamaindex.postgresHost | quote }}
  LLAMAINDEX_POSTGRES_PORT: {{ .Values.config.llamaindex.postgresPort | quote }}
  LLAMAINDEX_POSTGRES_DATABASE: {{ .Values.config.llamaindex.postgresDatabase | quote }}
  LLAMAINDEX_POSTGRES_USER: {{ .Values.config.llamaindex.postgresUser | quote }}
