bases:
  - bases/environments.yaml

helmDefaults:
  timeout: 600
  wait: true
  createNamespace: true

repositories:
  - name: cnpg
    url: https://cloudnative-pg.github.io/charts
  - name: kedacore
    url: https://kedacore.github.io/charts
  - name: dragonfly
    url: https://dragonflydb.github.io/dragonfly-operator

releases:
  - name: cnpg-operator
    namespace: cnpg-system
    chart: cnpg/cloudnative-pg

  - name: cnpg-cluster
    namespace: database
    chart: cnpg/cluster
    needs:
      - cnpg-system/cnpg-operator
    values:
      - values/cnpg-cluster/defaults.yaml
      - values/cnpg-cluster/{{ .Environment.Name}}.yaml

  - name: dragonfly-operator
    namespace: dragonfly-system
    chart: dragonfly/dragonfly-operator
    version: v1.1.8

  - name: dragonfly
    namespace: queue
    chart: dragonfly/dragonfly
    version: v1.1.8
    needs:
      - dragonfly-system/dragonfly-operator
    values:
      - values/dragonfly/defaults.yaml
      - values/dragonfly/{{ .Environment.Name }}.yaml

  - name: keda
    namespace: keda
    chart: kedacore/keda

  - name: lightrag
    namespace: lightrag
    chart: /tmp/lightrag-repo/k8s-deploy/lightrag
    needs:
      - database/cnpg-cluster
    values:
      - values/lightrag/defaults.yaml
      - values/lightrag/{{ .Environment.Name }}.yaml

  - name: gateway
    namespace: mycontextprotocol
    chart: ./charts/gateway
    needs:
      - database/cnpg-cluster
      - queue/dragonfly
    values:
      - values/common.yaml
      - values/gateway/{{ .Environment.Name }}.yaml
    secrets:
      - secrets/common.yaml
      - secrets/gateway/{{ .Environment.Name }}.yaml

  - name: worker
    namespace: mycontextprotocol
    chart: ./charts/worker
    needs:
      - database/cnpg-cluster
      - queue/dragonfly
      - keda/keda
    values:
      - values/common.yaml
      - values/worker/{{ .Environment.Name }}.yaml
    secrets:
      - secrets/common.yaml
      - secrets/worker/{{ .Environment.Name }}.yaml
