replicas: 1

image:
  repository: docker.dragonflydb.io/dragonflydb/dragonfly

resources:
  requests:
    cpu: 100m
    memory: 256Mi
  limits:
    cpu: 500m
    memory: 512Mi

authentication:
  passwordSecret: dragonfly-password
